version: '3.9'

services:
  elsadashboard:
    image: elsaworkflows/elsa-dashboard:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
        ELSA__SERVER__BASEADDRESS: "https://localhost:5001"           
    ports:
    - "14000:80"
  smtp4dev:
    image: rnwood/smtp4dev:linux-amd64-3.1.0-ci0856
    ports:
      - "3000:80"
      - "2525:25"