# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - vue-core

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./vuecore

    steps:
    - uses: actions/checkout@v2

    # - name: Set the value
    #   id: step_one
    #   run: |
    #     echo ("action_state=yellow") >> $env:GITHUB_ENV

    # - name: Use the value
    #   id: step_two
    #   run: |
    #     echo "${{ env.action_state }}" # This will output 'yellow'


# - run: |
#    chcp 65001 #set code page to utf-8
#    echo ("BRANCH_NAME=" + $env:GITHUB_REF.replace('refs/heads/', '')) >> $env:GITHUB_ENV

# - run: echo "${{ env.BRANCH_NAME }}"
# - run: echo $env:BRANCH_NAME
        # echo "tag=${GITHUB_REF#refs/*/}" >> $env:GITHUB_ENV

    - name: Set Tag Name
      run: |
        echo "(tag=${env.GITHUB_REF#refs/*/})" >> $env:GITHUB_ENV

    - name: Check Tag Name
      # env:
      #   RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo ${{ env.tag }}


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        include-prerelease: true

    - name: Install dotnet setversion
      run:  dotnet tool install -g dotnet-setversion

    - name: Set up NPM
      uses: actions/setup-node@v2
      with:
        node-version: 10.15.1
    - run: npm install

    - name: Build Vue
      # uses: actions/setup-node@v2
      run: npm run build:parcel

    - name: Update version from git tag
      run: setversion ${{env.tag}} VueCore.csproj

    - name: Build with dotnet
      # uses: actions/setup-dotnet@v1
      run: dotnet build --configuration Release

    - name: dotnet publish
      # uses: actions/setup-dotnet@v1
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/publish

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vue-core'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d5e7ba221cd74114ae48982eefddbbbf }}
        package: .